# https://stackoverflow.com/a/51437525
version: "3.8"
services:
  mysql:
    image : mysql
    container_name: mysql-demo-spring-boot-0
    environment:
    - PUID=1000
    - PGID=1000
    - "MYSQL_DATABASE=demo_spring_boot_0"
    - "MYSQL_USER=demo_spring_boot_0"
    - "MYSQL_PASSWORD=123456"
    - "MYSQL_ROOT_PASSWORD=123456"
    volumes:
    - ./db/mysql:/var/lib/mysql
    ports:
    - 3307:3306
    # restart: unless-stopped